apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-worker
  template:
    metadata:
      labels:
        app: nlp-worker
    spec:
      containers:
<<<<<<< HEAD
      - name: nlp-worker-container
        image: atharvaramawat/nlp-doc-intel:latest 
        command: ["python", "-u", "worker.py"]
=======
      - name: nlp-worker
        image: atharvaramawat/nlp-doc-intel:0048850
        imagePullPolicy: Always
        command: ["python", "worker.py"] 
>>>>>>> 004885080178c9fe9e3f0ab11a6f7b42c435c05b
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: DB_HOST
          value: "postgres-service"
        - name: MINIO_HOST
          value: "minio-service:9000"